### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by GiGaMo24-ZZ** [Zydratex/Gotcha#8]
Since this is depend on image detection, would it be possible to detect the pokecord name first or pokecord pfp first? after the bot detect the pfp or name , the bot would try to detect the spawn. 

And i still didnt manage to get a catch tho. if im gonna make my own img, does the image need to be like yours or it can detect the whole pokemon image?

**Comment by OniSensei** [comment]
@GiGaMo24 
Detecting if the Pokecord bot sent a message is very possible, and something I will definetly think about implimenting in the future. Since I can use the discord.net library to intercept messages I can even make that check if it is a spawn and remove the need for the image check on that part. **Great Suggestion**.


If you make your own image I would suggest making it 50x50 and make sure it doesn't include anything that is to specific. You want the bot to be able to detect a general spawn, and that the same goes for the pokemon image. A smaller but distinct image is best for detection.


I am offering support for fixing pokemon images via discord if you need any help fixing / setting this up. I have coded a standalone image scraper for this but it takes a bit of setup, I will likely add this to the bot as well to make things easier. My discord is on my profile here.

**Comment by GiGaMo24-ZZ** [comment]
Aight. thanks for the news and clarifications. gonna try the new update first.

**Comment by GiGaMo24-ZZ** [comment]
@Zydratex
Everything seems pretty fine. the bot seems to catch the mons. only the stats is bug or actually it wasn't the stats got problem.

The bot still can't differentiate the already caught pokemon. Making it trying to catch it again and adding the number to stats. Although the stats wasn't needed but knowing how many you got last night makes me happy.

My suggestion is to add auto 'p!info latest' after caught until you know the other work around for this issue.

**Comment by OniSensei** [comment]
@GiGaMo24 I normally suggest that you make the window size for the discord client a bit smaller.

This is how i have mine for example, you can see that after the pokemon is caught the top portion is cut off so it wont try to recapture.

![https://i.imgur.com/yPVeP01.png](https://i.imgur.com/yPVeP01.png)


Ive been updating the FAQ as things come up so please dont hessitate to post issues.
https://github.com/Zydratex/Gotcha/wiki/F.A.Q

**Comment by devadula-nandan** [comment]
scrape bot not online?

**Comment by OniSensei** [comment]
>scrape bot not online? ...

@devadula-nandan it’s working for me currently? Care to open a new ticket and post some details. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
